[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node .output/server/index.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
[services.healthcheck]
path = "/"
initialDelaySeconds = 10
timeoutSeconds = 10
