/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtrasRouteImport } from './routes/extras'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as PaisRouteImport } from './routes/pais'
import { Route as CapituloIdRouteImport } from './routes/capitulo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrasRoute = ExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisRoute = PaisRouteImport.update({
  id: '/pais',
  path: '/pais',
  getParentRoute: () => rootRouteImport,
} as any)
const CapituloIdRoute = CapituloIdRouteImport.update({
  id: '/capitulo/$id',
  path: '/capitulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extras': typeof ExtrasRoute
  '/mapa': typeof MapaRoute
  '/pais': typeof PaisRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extras': typeof ExtrasRoute
  '/mapa': typeof MapaRoute
  '/pais': typeof PaisRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extras': typeof ExtrasRoute
  '/mapa': typeof MapaRoute
  '/pais': typeof PaisRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extras' | '/mapa' | '/pais' | '/capitulo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extras' | '/mapa' | '/pais' | '/capitulo/$id'
  id: '__root__' | '/' | '/extras' | '/mapa' | '/pais' | '/capitulo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtrasRoute: typeof ExtrasRoute
  MapaRoute: typeof MapaRoute
  PaisRoute: typeof PaisRoute
  CapituloIdRoute: typeof CapituloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extras': {
      id: '/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof ExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pais': {
      id: '/pais'
      path: '/pais'
      fullPath: '/pais'
      preLoaderRoute: typeof PaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulo/$id': {
      id: '/capitulo/$id'
      path: '/capitulo/$id'
      fullPath: '/capitulo/$id'
      preLoaderRoute: typeof CapituloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtrasRoute: ExtrasRoute,
  MapaRoute: MapaRoute,
  PaisRoute: PaisRoute,
  CapituloIdRoute: CapituloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
